Helper function for dropping timeslice
EnergySystemsModellingLab/MUSE_OS pull request #392
Opened 2024-07-02 12:56 UTC by tsmbland

# Description

Adds a helper function for dropping the timeslice variable from data arrays, and uses this throughout the code instead of `drop_vars(["timeslice", "month", "day", "hour"])`

This partially fixes #363, but a few other changes will be required which I'm addressing in #381

## Type of change

Please add a line in the relevant section of
[CHANGELOG.md](https://github.com/EnergySystemsModellingLab/MUSE_OS/blob/development/CHANGELOG.md) to
document the change (include PR #) - note reverse order of PR #s.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (non-breaking, back-end change that speeds up the code)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (whatever its nature)

## Key checklist

- [ ] All tests pass: `$ python -m pytest`
- [ ] The documentation builds and looks OK: `$ python -m sphinx -b html docs docs/build`

## Further checks

- [ ] Code is commented, particularly in hard-to-understand areas
- [ ] Tests added that prove fix is effective or that feature works

2024-07-02 14:20 UTC, dalonsoa requested changes
Given that you're on it, add a dedicated tests that checks the new function.

2024-07-02 14:20 UTC, dalonsoa commented on src/muse/timeslices.py
> +def drop_timeslice(data: DataArray):
Ideally, add output type:
```suggestion
def drop_timeslice(data: DataArray) -> DataArray:
```

2024-07-02 14:31 UTC, alexdewar approved these changes
I've made a small suggestion (that probs won't work) but other than that, LGTM.

2024-07-02 14:31 UTC, alexdewar commented on src/muse/timeslices.py
> +    return data.drop_vars([c for c in data.timeslice.indexes])
Would this work:

```suggestion
    return data.drop_vars(data.timeslice.indexes)
```

If not, how about:

```suggestion
    return data.drop_vars(list(data.timeslice.indexes))
```

2024-07-04 08:03 UTC, tsmbland commented
@dalonsoa Would you mind taking a quick look at this so I can merge it?

2024-07-04 08:10 UTC, dalonsoa approved these changes
LGTM! Sorry, I didn't realized the changes had been implemented.

2024-07-04 08:23 UTC, merged